### ISSUE TITLE
Error if the value is null and the schema expects a different thing

### ISSUE THREAD

**Issue by alexgmin** [bhch/django-jsonform#121]
WIth this schema:
```
    field = NullableJSONFieldWithSchema(
        default=None,
        blank=True,
        null=True,
        schema={
            'type': 'object',
            'keys': {
                'foo': {
                    'type': 'array',
                    'items': {
                        'type': 'object',
                        'keys': {},
                        'additionalProperties': {
                            'anyOf': [
                                {
                                    'title': 'String',
                                    'type': 'string',
                                },
                            ],
                        },
                    },
                }
            }
        },
    )
 ```

If the value of the field in database is `{'foo': None}`, the following happens:
![image](https://github.com/bhch/django-jsonform/assets/8340441/9668febe-1c6f-4772-a639-beb803bf4ff9)

If you update the value only via the admin it will never be null but if you update via outside sources it could be, so maybe there's should be an option to indicate that a certain key is nullable.

**Comment by bhch** [comment]
What do you think if the form should implicitly convert the data from `{"foo": null}` to `{"foo": []}` when it renders?

**Comment by alexgmin** [comment]
That would work too, but I'm not sure if in more complex schemas or other use cases the nullable property would be better.

**Comment by bhch** [comment]
You mean something like this:  `{'type': ['array', 'null']}`? Related: issue #113.

Only way I can think of to make it work is by allowing the user to select/toggle between the types, similar to how `oneOf` works. What do you think of this?

**Comment by bhch** [comment]
I've tried to address this in the new release [v2.20.0](https://github.com/bhch/django-jsonform/releases/tag/v2.20.0). The form is now a bit more tolerant if it receives `null` when it expects something else. In that case, it will implicitly replace `null` with appropriate/expected data type.

I've also tested it with some complex, deeply nested schemas and this seems to work well.

Supporting multiple types requires a rewrite of significant portion of the core which I didn't think was worth it since it's a rare use case.

For now, I'll close this issue. But if you should find some cases where it doesn't work, feel free to re-open the issue.

Please upgrade and test it out.

Thank you.
