### ISSUE TITLE
Custom validation of object properties not showing error next to field

### ISSUE THREAD

**Issue by captain828** [bhch/django-jsonform#141]
**Schema:**
```
{
    'type': 'object',
    'properties': {
        'my_prop': {
            'type': 'string',
            'helpText': 'Some help text.',
            'required': True
        }
    }
}
```
**Custom validation inside model:**
```
def clean(self):
  error_map = ErrorMap()
  key = 'my_prop'
  url = self.config[key]
  try:
      URLValidator()(url)
  except ValidationError:
      error_message = _('URL is invalid')
      error_map.set(coords=[key], msg=error_message)
      raise JSONSchemaValidationError(
          error_message,
          error_map=error_map
      )
```
**Tests:**
- submitting the form with no values - ***PASS***
![image](https://github.com/bhch/django-jsonform/assets/17725004/5e7aa796-f8d4-4d66-9e04-4b8b9ec8d39e)

- submitting the form with data that would fail the validation - ***FAIL***
![image](https://github.com/bhch/django-jsonform/assets/17725004/a39ec9dc-5fd2-4054-a22e-f5df6d3e2617)

**Expected result:**
- the custom error message is shown next to the field in the same way as the required validation 

**Versions:**
- django-jsonform: 2.21.5
- django-semantic-admin: 0.4.0 (tried without as well and same effect)
- django: 5.0
- python: 3.12.1

---
The only thing I can think of is that `coords=[key]` isn't correct but the docs don't cover this simple case (they focus on an array with an object inside) and all the other ways I've tried didn't work.

**Comment by bhch** [comment]
Doing this inside a model's `clean` method isn't possible because then the validation will be handled by the model (not the json field). So the model doesn't pass the `error_map` object over to the json field.

What we want to do is to make this validation at the field level. So that field can catch the exception early and use the `error_map`.

So, you are required to create a custom form for this and set a custom validator on the json field. See docs: https://django-jsonform.readthedocs.io/en/latest/guide/validation.html#creating-a-form

**Comment by captain828** [comment]
Awesome, thanks for clarifying!
