### ISSUE TITLE
Meta-Schema: JSON validation with JSON Schema draft definition

### ISSUE THREAD

**Issue by perrotuerto** [bhch/django-jsonform#173]
I want users to write their own JSON schemes, so for the `schema` key I tried to use [`jsonschema.validators.Draft202012Validator.META_SCHEMA`](https://python-jsonschema.readthedocs.io/en/stable/api/jsonschema/validators/#jsonschema.validators.Draft202012Validator) without success.

I saw [in the docs](https://django-jsonform.readthedocs.io/en/latest/schema.html) that there are diffs between this implementation and the standard spec. I also read in #127 that referencing external files are not supported (and, therefore, `jsonschema.validators.Draft202012Validator.META_SCHEMA` is not supported).

It is fine for my use case if this implementation is not exactly as the standard spec.

So what I want to know is:

What can I use as schema so I can validate user writings of their own JSON schemes, is there a "meta schema" I can use?

Thanks for this great work, @bhch!

**Comment by sevdog** [comment]
This may be addressed by using [jsonschema](https://pypi.org/project/jsonschema/) or [fastjsonschema](https://pypi.org/project/fastjsonschema/) instead of the [custom implementation](https://github.com/bhch/django-jsonform/blob/465ddd6a367d1eb9a63dac4e6de44e0542128f01/django_jsonform/validators.py#L13) which is provided by this package.

What is the meaning of writing froom scratch a jsonschema validator when there are others already working?

**Comment by perrotuerto** [comment]
Thanks for you reply! At the end I saw that my target user would struggle understanding JSON Schemata, so instead I defined some objects (such as "text", "number", "list", and so on) that the user can use in order to create their own forms.

Great project, thanks :D
