### ISSUE TITLE
2 array field in one row (fieldset)

### ISSUE THREAD

**Issue by zN3utr4l** [bhch/django-jsonform#47]
I didn't pass any custom css or attr style to widget to make it format, I just formatted the 2 array fields on a single line using fieldsets.

![image](https://user-images.githubusercontent.com/73225008/184314617-bebcf403-7192-49d5-9925-6648b3dd1cf2.png)

![image](https://user-images.githubusercontent.com/73225008/184314469-82b1c398-1b3e-4c1a-80b9-8a9838e4c41a.png)
![image](https://user-images.githubusercontent.com/73225008/184314936-46f2e4ea-6422-47b9-840e-37b6a47168f7.png)

**Comment by bhch** [comment]
I'll try to fix it, but don't depend on it.

The problem here is that Django admin's default CSS is not using `box-sizing: border-box` and using fixed widths. So, to keep the widget's ui similar to the Django admin's, we also have to use fixed widths instead of percentage values which will give us a better, responsive styling.

I mean, I can fix it for this case but it will break again if you include three fields in a row. It's difficult to account for every case without using percentages.

**Comment by bhch** [comment]
I've made some improvements to the CSS in [v2.11.0](https://github.com/bhch/django-jsonform/releases/tag/v2.11.0). Please upgrade.
