### ISSUE TITLE
[Resolved] How to override the `to python` and `to db` serialization and deserialization?

### ISSUE THREAD

**Issue by gary-arcana** [bhch/django-jsonform#74]
For my specific use case, I am combining your library with https://github.com/s-knibbs/dataclasses-jsonschema
So, I am trying to have it serialize/deserialize to/from the dataclass.

In the python code, I want to get a dataclass instance when I access `.field` and I also want to be able to do `.field = dataclass_instance`

I do not want to affect the behavior on Django Admin.

# My attempt at overriding:

But it doesn't seem to do anything for the python code. `MyModel.objects.first().my_field` still returns a dict

```python
class JSONFormField(JSONField):

    def __init__(self, dataclass_cls, **kwargs):
        super().__init__(schema=dataclass_cls.json_schema(), **kwargs)

    def to_python(self, value):
        raise ValueError('hello')
        return value

    def get_prep_value(self, value):
        raise ValueError('hello2')
        return value
```

**Comment by gary-arcana** [comment]
Ah, I was looking at the wrong thing

Should be

```python
class JSONFormField(JSONField):

    def __init__(self, dataclass_cls, **kwargs):
        super().__init__(schema=dataclass_cls.json_schema(), **kwargs)

    def from_db_value(self, value, expression, connection):
        print('what up')
        return value

    def get_prep_value(self, value):
        print('hello')
        return value
```

**Comment by bhch** [comment]
I must alert you that django-jsonform doesn't support all the standard JSON schema features. We've implemented a custom spec which is more suitable for form generation, rather than JSON data validation.

For example, listing required fields in an array is not supported. To make a field required, you have to set the `required` keyword inside the field:

```python
# won't work
{
    ...
    'required': ['field1', 'field2', ...]
}

---

# will work
{
    ...
    'field1': {'required': True},
    'field2': {'required': True}
} 
```

Although, the final goal is to fully support the standard schema, but it's still quite some way off.

**Comment by dongyuzheng** [comment]
I am @ghost
